# You should only have to change this value:
PORT = /dev/tty.usbserial-DNWYFIDM

# Set this depending on what revision of the PCB you are using. 1.3 is equal to 13 etc.
BOARD_SUB = balanduino.menu.rev.rev13
#BOARD_SUB = balanduino.menu.rev.rev12

# You should only set the path to your Arduino application if it is not in your path or not the default one:
# The default for Linux and Solaris is:
#ARD_HOME = /opt/Arduino
# The default for Mac is:
#ARD_HOME = /Applications/Arduino.app

# Uncomment to activate serial debugging for the USB Host library:
#EXTRA_FLAGS += -D DEBUG_USB_HOST

# Leave these alone
THIRD_PARTY_HARDWARE = ../hardware/Balanduino/avr
BOARD = balanduino

include Arduino_Makefile_master/_Makefile.master