# You should only have to change these two values
PORT = /dev/tty.usbserial-A501I130
ARD_HOME = /Applications/Arduino1.0.5.app/Contents/Resources/Java

# Leave these alone
THIRD_PARTY_HARDWARE = ../hardware/Balanduino
BOARD = balanduino
MON_SPEED = 57600
LIB_DIRS = ../libraries/USB_Host_Shield_2.0
LIB_DIRS += ../libraries/KalmanFilter
LIB_DIRS += ../hardware/Balanduino/avr/libraries/Wire
LIB_DIRS += ../hardware/Balanduino/avr/libraries/Wire/utility
include Makefile.master